require "yaml"

require "devup/compose"
require "devup/service"
require "devup/service_presenter"

module Devup
  class Environment
    attr_reader :pwd, :compose

    def initialize(pwd:, compose: nil)
      @pwd = pwd.to_s.strip
      @compose = compose || Compose.new(root.join("docker-compose.yml"), project: project)
    end

    def project
      pwd.split("/")[-1].strip
    end

    def env
      services.map { |s| service_env(s) }.join("\n\n")
    end

    def up
      compose.up
      write_dotenv
    end

    def down
      compose.stop
      compose.rm
      clear_dotenv
    end

    def root
      Pathname.new pwd
    end

    private

    def services
      @services ||= compose.services.map { |name| Service.new(compose, name) }
    end

    def service_env(service)
      ServicePresenter.new(service, project: project).call
    end

    def write_dotenv
      File.open(root.join(".env.services"), "w") { |f| f.write dotenv }
    end

    def clear_dotenv
      File.open(root.join(".env.services"), "w") { |f| f.write "" }
    end

    def dotenv
      <<~DOTENV
        ####################################################
        #     This file is generated by devup command.     #
        #     Home: https://github.com/sergio-fry/devup    #
        ####################################################
        # START

        #{env}

        # END

      DOTENV
    end
  end
end
